function displayDealtCard(card)
    %use the card to find the last 5 letters in the element
    card = convertStringsToChars(card);
    cardSuit = card((strlength(card)-4):strlength(card));
    %For each case of string create an ASCII art creation
    switch(cardSuit)
        %Make box for each one dependant on position and size of central
        %text as matlab does not except emojis
        case 'Clubs'
            fprintf([' ____\n' ...
            '|%s   |\n' ...
            '|%s|\n' ...
            '|___%s|\n' ...
            ], card(1:2), card((strlength(card)-4):strlength(card)), card(1:2))
        case 'monds'
            fprintf([' _______\n' ...
            '|%s      |\n' ...
            '|%s|\n' ...
            '|______%s|\n' ...
            ], card(1:2), card((strlength(card)-7):strlength(card)), card(1:2))
        case 'earts'
            fprintf([' _____\n' ...
                '|%s    |\n' ...
                '|%s|\n' ...
                '|____%s|\n' ...
                ], card(1:2), card((strlength(card)-5):strlength(card)), card(1:2))
        case 'pades'
            fprintf([' _____\n' ...
                '|%s    |\n' ...
                '|%s|\n' ...
                '|____%s|\n' ...
                ], card(1:2), card((strlength(card)-5):strlength(card)), card(1:2))
     end